services:
  clam_casino_server:
    container_name: clam_casino_server
    build: .
    ports:
      - "8000"
    restart: always
    volumes:
      - ./clam_casino_server/data:/data

    environment:
        # provides the solution as a /flip response even before the game ends
        - CLAMCASINO_DEBUG=1
        # UNCOMMENT THE FOLLOWING LINE AND SET YOUR URL FOR PRODUCTION
        # - ALLOWED_ORIGINS=http://url.com

  clam_casino_proxy:
    container_name: clam_casino_proxy
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - clam_casino_server
    restart: always
