services:
  clam_casino_server:
    container_name: clam_casino_server
    build: .
    ports:
      - "8000"
    restart: always
    volumes:
      - clam_casino_data:/data

    environment:
        - ALLOWED_ORIGINS=https://localhost,https://kitsu.croco.dev

        # Provides the solution as a /flip response even before the game ends.
        - CLAMCASINO_DEBUG=1

        #
        # GAME CONFIGURATION
        #

        # Number of days to keep keep cookies (persistent scores) until they expire.
        - COOKIE_SHELFLIFE=30

        # Number of rows and columns in each board. 6 represents a 6x6 grid.
        - BOARD_SIZE=6

        # Use card distributions and levels from the original Voltorb Flip game.
        # (overrides all values after)
        - USE_VTFLIP_VALS=0

        # Max level you wish the player to be able to choose (0 indexed).
        # Currently, only values 0-7 are designed to work.
        - MAX_LEVEL=7

        # Number of 0 cards generated per board, per level.
        - L0_ZEROS=6
        - L1_ZEROS=7
        - L2_ZEROS=8
        - L3_ZEROS=9
        - L4_ZEROS=10
        - L5_ZEROS=11
        - L6_ZEROS=12
        - L7_ZEROS=13

        # This is the maximum score that should be able to be earned per level.
        # The board generator may create boards less than this value, but
        # never exceed it. Zero cards take priority. 
        - L0_MAXSCORE=48
        - L1_MAXSCORE=96
        - L2_MAXSCORE=192
        - L3_MAXSCORE=324
        - L4_MAXSCORE=576
        - L5_MAXSCORE=972
        - L6_MAXSCORE=1728
        - L7_MAXSCORE=3456

  clam_casino_proxy:
    container_name: clam_casino_proxy
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./html:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - clam_casino_server

volumes:
  caddy_data:
  caddy_config:
  clam_casino_data:
